[tox]  
requires =  
    tox>=4
    tox-uv>=1.25.0
env_list =   
    py{310,311,312}  
    lint  
    type  
    coverage  
isolated_build = True
  
[testenv] 
runner = uv-venv-lock-runner
description = Run tests using uv and pytest
skip_install = true  
; allowlist_externals = uv
commands_pre =  
    uv pip install -e ".[dev]"  
commands =   
    uv run pytest -v {posargs:tests}  
  
; [testenv:type]  
; description = run type checks  
; skip_install = true  
; allowlist_externals = uv 
; commands_pre =  
;     uv pip install -e ".[dev]"  
; commands =  
;     uv run mypy {posargs:mansa tests}  
  
[testenv:lint]  
runner = uv-venv-lock-runner
description = Run ruff using uv
skip_install = true  
; allowlist_externals = uv  
commands_pre =  
    uv pip install -e ".[dev]"  
commands = uv run ruff check 
  
[testenv:coverage]  
runner = uv-venv-lock-runner
description = run coverage report  
skip_install = true  
; allowlist_externals = uv  
commands_pre =  
    uv pip install -e ".[dev]"  
commands = uv run pytest -v --cov=. --cov-report=xml

[gh]
python =
    3.12 = py312
    3.11 = py311
    3.10 = py310