[classes]
names = [
    "ComputeInstance",
    "AmlComputeProvisioningConfiguration",
    "ComputeCluster",
    "BatchDeployment",
    "BatchEndpoint",
    "ManagedOnlineEndpoint",
    "ModelBatchDeployment",
    "OnlineDeployment",
    "OnlineEndpoint",
    "PipelineComponent",
    "PipelineComponentBatchDeployment",
    "Deployment",
    "Jobs",
    "AzureOpenAIDeployment",
    "ServerlessEndpoint"
]

